import json
import os
import boto3
from decimal import Decimal

dynamodb = boto3.resource("dynamodb")
ses = boto3.client("ses")
table = dynamodb.Table("ReadyCheckSessions")

SENDER_EMAIL = os.environ["SENDER_EMAIL"]
NOTIFY_EMAIL = os.environ["NOTIFY_EMAIL"]

CATEGORIES = [
    "integration_asked",
    "scale_asked",
    "compliance_asked",
    "success_metric_asked",
    "stakeholders_asked",
    "timeline_asked",
]


def extract_fields(body):
    """
    Field extraction priority:
    1. trainee_email / trainee_name — always read from
       data.conversation_initiation_client_data.dynamic_variables, which
       ElevenLabs populates with the known values passed at widget init time.
       These fields are never spoken in the conversation so Data Collection
       can never capture them reliably.
    2. All other fields (scenario, booleans, etc.) — read from
       data.analysis.data_collection_results, which is where ElevenLabs
       puts post-call LLM extraction results.
    3. Flat top-level keys — fallback for direct curl tests.
    """
    # --- dynamic variables (trainee identity) ---
    dyn_vars = {}
    try:
        dyn_vars = body["data"]["conversation_initiation_client_data"]["dynamic_variables"]
    except (KeyError, TypeError):
        pass

    # --- Data Collection results ---
    dc_results = {}
    try:
        dc_results = body["data"]["analysis"]["data_collection_results"]
    except (KeyError, TypeError):
        pass

    def get_dc(key, default=""):
        """Read from Data Collection results, fall back to flat body.
        Booleans from LLM come as strings ("true"/"false") — normalise them.
        """
        if key in dc_results:
            entry = dc_results[key]
            if isinstance(entry, dict) and "value" in entry:
                val = entry["value"]
            else:
                val = entry
        else:
            val = body.get(key, default)
        # Normalise string booleans returned by the LLM
        if isinstance(val, str):
            if val.lower() == "true":
                return True
            if val.lower() == "false":
                return False
        return val

    # Log what we found so payload shape issues are easy to diagnose
    print("DEBUG dynamic_variables:", dyn_vars)
    print("DEBUG dc_results keys:", list(dc_results.keys()))

    # --- transcript_summary from ElevenLabs auto-analysis ---
    transcript_summary = ""
    try:
        transcript_summary = body["data"]["analysis"].get("transcript_summary", "") or ""
    except (KeyError, TypeError):
        pass

    return {
        # Identity: from dynamic_variables first, Data Collection as fallback
        "trainee_email": dyn_vars.get("trainee_email") or get_dc("trainee_email"),
        "trainee_name": dyn_vars.get("trainee_name") or get_dc("trainee_name"),
        # Session fields: from Data Collection
        "scenario_type": get_dc("scenario_type"),
        "stakeholder_type": get_dc("stakeholder_type"),
        "communication_style": get_dc("communication_style"),
        "integration_asked": get_dc("integration_asked", False),
        "scale_asked": get_dc("scale_asked", False),
        "compliance_asked": get_dc("compliance_asked", False),
        "success_metric_asked": get_dc("success_metric_asked", False),
        "stakeholders_asked": get_dc("stakeholders_asked", False),
        "timeline_asked": get_dc("timeline_asked", False),
        "critical_detail_asked": get_dc("critical_detail_asked", False),
        "adaptive_follow_up": get_dc("adaptive_follow_up", False),
        "flagged_quote": get_dc("flagged_quote"),
        "key_takeaway": get_dc("key_takeaway"),
        "debrief_summary": get_dc("debrief_summary"),
        # Auto-generated by ElevenLabs post-call analysis
        "transcript_summary": transcript_summary,
    }


def score_session(data):
    covered = sum(1 for c in CATEGORIES if data.get(c) is True)
    completeness_pct = round((covered / len(CATEGORIES)) * 100)
    adaptive_follow_up = bool(data.get("adaptive_follow_up", False))
    missing = [c.replace("_asked", "") for c in CATEGORIES if not data.get(c)]
    ready_for_poc = completeness_pct >= 66 and adaptive_follow_up

    return {
        "discovery_completeness_pct": completeness_pct,
        "adaptive_follow_up": adaptive_follow_up,
        "ready_for_poc": ready_for_poc,
        "missing_categories": missing,
    }


def write_to_dynamodb(trainee_email, first_name, data, result):
    item = {
        "trainee_email": trainee_email,
        "first_name": first_name,
        "stakeholder_type": data.get("stakeholder_type", ""),
        "communication_style": data.get("communication_style", ""),
        "flagged_quote": data.get("flagged_quote", ""),
        "key_takeaway": data.get("key_takeaway", ""),
        "debrief_summary": data.get("debrief_summary", ""),
        "transcript_summary": data.get("transcript_summary", ""),
        **{k: (Decimal(str(v)) if isinstance(v, (int, float)) and not isinstance(v, bool) else v)
           for k, v in result.items() if k != "missing_categories"},
        "missing_categories": result["missing_categories"],
    }
    table.put_item(Item=item)


def send_email(display_name, data, result):
    verdict = "READY FOR POC" if result["ready_for_poc"] else "NOT YET READY"
    missing_str = ", ".join(result["missing_categories"]) or "none"

    # Priority: ElevenLabs auto-generated transcript summary →
    #           custom debrief_summary from Data Collection →
    #           plain templated fallback
    transcript_summary = (data.get("transcript_summary") or "").strip()
    debrief_summary = (data.get("debrief_summary") or "").strip()

    if transcript_summary:
        summary_section = transcript_summary
    elif debrief_summary:
        summary_section = debrief_summary
    else:
        summary_section = (
            f"You covered {result['discovery_completeness_pct']}% of the key "
            f"discovery areas this session. Next time, focus on: {missing_str}."
        )

    body = f"""Ready Check — Your Discovery Report Card

{summary_section}

--- Session Detail ---
Stakeholder: {data.get('stakeholder_type', '')}
Communication Style: {data.get('communication_style', '')}
Discovery Completeness: {result['discovery_completeness_pct']}%
Verdict: {verdict}
"""

    ses.send_email(
        Source=SENDER_EMAIL,
        Destination={"ToAddresses": [NOTIFY_EMAIL]},
        Message={
            "Subject": {"Data": f"Your Ready Check report card, {display_name}"},
            "Body": {"Text": {"Data": body}},
        },
    )


def lambda_handler(event, context):
    raw_body = json.loads(event.get("body") or "{}")

    # Temporary full-payload debug — remove once payload shape is confirmed
    try:
        data_keys = list(raw_body.get("data", {}).keys())
        analysis_keys = list(raw_body.get("data", {}).get("analysis", {}).keys()) if "analysis" in raw_body.get("data", {}) else "no analysis key"
        conv_init = raw_body.get("data", {}).get("conversation_initiation_client_data", "missing")
        print("DEBUG data keys:", data_keys)
        print("DEBUG analysis keys:", analysis_keys)
        print("DEBUG conversation_initiation_client_data:", conv_init)
    except Exception as e:
        print("DEBUG inspection error:", e)

    data = extract_fields(raw_body)

    trainee_email = (data.get("trainee_email") or "").strip().lower()
    if not trainee_email:
        # Never let an empty partition key value reach put_item — that
        # crashes with ValidationException and blocks everything,
        # including the email. Fall back to a synthetic key and log
        # loudly so the real cause (payload shape mismatch, or Data
        # Collection never capturing this field) is visible and fixable.
        conversation_id = raw_body.get("data", {}).get("conversation_id", "")
        trainee_email = f"unknown-{conversation_id or 'no-id'}"
        print(
            "WARNING: trainee_email was empty in the incoming payload — "
            "using fallback key. Raw body top-level keys:",
            list(raw_body.keys()),
        )

    first_name = data.get("trainee_name", "")
    display_name = first_name or trainee_email
    result = score_session(data)

    write_to_dynamodb(trainee_email, first_name, data, result)

    try:
        send_email(display_name, data, result)
        email_status = "sent"
    except Exception as e:
        # DynamoDB write already succeeded — don't let an SES failure
        # turn a partial success into a total failure.
        print("send_email failed:", e)
        email_status = f"failed: {e}"

    return {
        "statusCode": 200,
        "headers": {"Content-Type": "application/json"},
        "body": json.dumps({"status": "ok", "email_status": email_status, **result}),
    }
